### ISSUE TITLE
current events / event items should not include draft agendas

### ISSUE THREAD

**Issue by techieshark** [codeforamerica/MuniciPal#152]
Events and hence, event items, should only be included on the site for public consumption / participation if they are not `Draft` events.

Currently, if you click the example address and view the event items in the browser console you'll see that some are drafts:

![drafts](https://cloud.githubusercontent.com/assets/1072292/6783936/aeec73b8-d1d0-11e4-8cfe-6a361d67b5b7.png)

**Comment by techieshark** [comment]
I'm pushing a commit which seems to fix this; here's the browser console before:

![image](https://cloud.githubusercontent.com/assets/1072292/6784001/2a6537b4-d1d1-11e4-9f66-408af82ae025.png)

and after:

![image](https://cloud.githubusercontent.com/assets/1072292/6784004/32104e22-d1d1-11e4-8837-c590c14343f3.png)

**Comment by buckleytom** [comment]
yay!
