### ISSUE TITLE
invalid geojson object

### ISSUE THREAD

**Issue by buckleytom** [codeforamerica/MuniciPal#154]
it looks like ESRI/Mapbox issues are plaguing the site again?

**Comment by buckleytom** [comment]
another potential culprit? the url for Mesa's rest service for their boundary data is no longer valid:

https://services2.arcgis.com/1gVyYKfYgW5Nxb1V/ArcGIS/rest/services/MesaCouncilDistricts/FeatureServer/0/query?where=DISTRICT+IS+NOT+NULL&outSR=4326&f=json

**Comment by techieshark** [comment]
Thanks for looking into this, @buckleytom. 

I also noticed that Typekit giving access denied (perhaps it was never set up for the mesaaz.gov domain), and the fonts are falling back to system fonts. I'm putting together a new typekit kit for use over there now.

![image](https://cloud.githubusercontent.com/assets/1072292/7353112/8b4d3830-ed54-11e4-8fbc-66dc46b4d887.png)

**Comment by techieshark** [comment]
But that invalid response from the Mesa ESRI boundary service is definitely a problem.

![image](https://cloud.githubusercontent.com/assets/1072292/7353194/26d1e0ee-ed55-11e4-8d46-9b7424f14f1d.png)

@buckleytom any idea what that URL might not work any more?

**Comment by jcturner** [comment]
The issue with the Mesa ESRI boundary service has been fixed.  It was accidently deleted.  We added delete protection on the feature service this time, so hopefully this won’t happen again  Thanks for letting us know.

**Comment by buckleytom** [comment]
thanks @jcturner!
