### ISSUE TITLE
when clicking the link on the landing page on narrow screens, the page does not load the expected council district

### ISSUE THREAD

**Issue by buckleytom** [codeforamerica/MuniciPal#158]
saw this error on chrome on mobile and ios on mobile.

**Comment by techieshark** [comment]
confirmed; clicking on example address results in what appears to be a front page page-reload rather than jumping to a council district page.

**Comment by buckleytom** [comment]
i think it may only be the link action that does it? its also a problem on any browser of a certain size. e.g. if you scale chrome down to a small window and click the link.

**Comment by techieshark** [comment]
Thanks @buckleytom; I updated the description accordingly. It seems to relate to the fact that on small screens we're hiding the map, which is mucking with some Leaflet stuff and causing a JS error which prevents further progress.
