### ISSUE TITLE
Who maintains this app?

### ISSUE THREAD

**Issue by michaelhwan** [codeforamerica/MuniciPal#160]
Hey @techieshark @tombuckley @wendyfongsf,

Who maintains this app? Code for America or City of Mesa?

**Comment by techieshark** [comment]
Hey @michaelhwan good to see you on the interwebs. @vancefsmithmesa and @jcturner have made a number of useful [customizations](https://github.com/CityOfMesaAZ/MuniciPal/commits/mesa-customized) for the City's copy of this. Why do you ask? (Feel free to email me directly too.)

**Comment by michaelhwan** [comment]
@techieshark just making sure future pull requests from the Phoenix brigade doesn't go unanswered.

**Comment by techieshark** [comment]
Sweet. Pull requests from the brigade would be super! Just make sure they're responding to an open issue so we can keep discussion on issues (and feel free to open issues if there's something new to report / work on). I'll let you close this issue if you think it's resolved now. :)
